site_name: MDFTS
site_description: "Interface for integrated particle and field simulations"
site_url: "https://equalapriori.github.io/mdfts/"
repo_url: "https://github.com/EqualAPriori/mdfts"
repo_name: "mdfts"
site_dir: "site"

theme:
  name: material
    
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - codehilite

plugins:
  - mkdocs-jupyter
  - search
  - gen-files:
      scripts:
      - docs/gen_ref_nav.py
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          setup_commands:
          - import sys
          - sys.path.append("docs")
          selection:
            new_path_syntax: yes
          rendering:
            show_source: true
      watch:
        - src/mdfts

nav:
    - "Home": index.md
    - "Reference": 
        - "At a glance": reference/ToC.md
        - "Src": reference/

